stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: httpd:latest
      registry: 127.0.0.1:34675
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./httpd.yaml
- name: Criando Service PHP
  steps:
  - applyYamlConfig:
      path: ./php-apache-svc.yaml
  when:
    event:
      exclude:
      - push
timeout: 60
notification: {}
