stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: httpd:latest
      registry: 127.0.0.1:34675
- name: Deploy-httpd
  steps:
  - applyYamlConfig:
      path: ./httpd.yaml
  - applyYamlConfig:
      path: ./mysql.yaml
timeout: 60
notification: {}
