stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: httpd:latest
      registry: 127.0.0.1:34675
- name: Deploy-httpd
  steps:
  - applyYamlConfig:
      path: ./httpd.yaml
  - applyYamlConfig:
      path: ./mysql.yaml
- name: Test
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: curl -v https://apache.k8s-lab.com.br/
timeout: 60
notification: {}
