apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: tivit
  name: rabbitmq
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn