---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: tivit
  name: mysql-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi